import Head from "next/head";
import { Box, Button, Typography } from "@mui/material";
import { TableVideos } from "@app/presentantion/components/TableVideos";
import { UploadFile } from "@mui/icons-material";
import { useState } from "react";
import { FormVideo } from "@app/presentantion/components/FormVideo";

export default function Home() {
  const [openForm, setOpenForm] = useState(false);
  return (
    <>
      <Head>
        <title>Administrador | Creador de videos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Box
          my={2}
          style={{
            flexDirection: "row",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <Typography variant="h6">{"Creador de videos"}</Typography>

          <Button
            variant="outlined"
            endIcon={<UploadFile />}
            onClick={() => setOpenForm(true)}
          >
            Cargar video
          </Button>
        </Box>
        <TableVideos />
        <FormVideo onClose={() => setOpenForm(false)} open={openForm} />
      </Box>
    </>
  );
}
